spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fichas
    url: mysql://b46d5ffce431c2:223d2ae3@us-cdbr-east-03.cleardb.com/heroku_d4ddeed93d4f3ea?reconnect=true
#    username: root
#    password: 123456
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
  secret: m1nh4sf1ch4s